max_num_landmarks: 7
num_landmarks: 5
horizon: 50
env_width: 10
env_height: 10
tau: 1.0

motion:
  A:
    _1: 1
    _2: 1
  B:
    _1: 1
    _2: 1
  W:
    _1: 0.005
    _2: 0.005
  landmark_motion_scale: 0.3

init_info: 0.001

FoV:
  radius: 3
  psi: 0.5235987755982988
  kappa: 1.0
  V:
    _1: 0.01
    _2: 0.01

lr: 0.0003
max_epoch: 2000
batch_size: 20
num_test_trials: 20
