max_num_landmarks: 7
num_landmarks: 5
horizon: 50
env_width: 10
env_height: 10
tau: 1.0

motion:
  A:
    _1: 1
    _2: 1
  B:
    _1: 1
    _2: 1
  W:
    _1: 0.0025
    _2: 0.0025
  landmark_motion_scale: 1

init_info: 0.5

FoV:
  radius: 2
  psi: 1.0471975511965976
  kappa: 0.4
  V:
    _1: 0.04
    _2: 0.04

lr: 0.0003
max_epoch: 1000
batch_size: 60
num_test_trials: 20
